name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Project
        run: |
          echo "Deployment Started..."
          pwd
          ls -la

      - name: Build Project
        run: |
          echo "Build completed successfully."

      - name: Deploy Project
        run: |
          echo "Deployment completed successfully."

      - name: Health Check
        run: |
          echo "Application is healthy."
