name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
      - main

  push:
    branches:
      - develop

jobs:

  frontend:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build Next.js
        run: npm run build

  backend:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Lint
        run: |
          pip install flake8
          flake8 .

      - name: Run Tests
        run: |
          pip install pytest
          pytest

  docker:

    needs:
      - frontend
      - backend

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Build Docker Images
        run: docker compose build
